title: REFACTOR
email: rwilhelmy@gmail.com
description: > 
  Historias de un hacker cívico dentro de Gobierno.
baseurl: "/refactor"
url: "http://rodowi.github.io"
twitter_username: rodowi
github_username:  rodowi

# Build settings
markdown: kramdown
