title: REFACTOR
email: rwilhelmy@gmail.com
description: > 
  En temas de Gobierno Abierto y Digital hay mucha retórica 
  pero poca implementación.
  Aquí platicamos de cómo hacer hacking cívico desde dentro de gobierno.
baseurl: "/refactor"
url: "http://rodowi.github.io"
twitter_username: rodowi
github_username:  rodowi

# Build settings
markdown: kramdown
